modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/Abbie5/emi-ores/issues"

[[mods]]
modId = "emi_ores"
version = "${version}"
displayName = "EMI Ores"
description = "Easily view ore generation information from inside EMI."
authors = "Abbie"
logoFile = "icon.png"
logoBlur = false
displayURL = "https://modrinth.com/mod/emi-ores"

[[dependencies.emi_ores]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emi_ores]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.emi_ores]]
modId = "emi"
type = "required"
versionRange = "${neoforge_emi_version}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "emi_ores.mixins.json"
