name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: var
        run: echo "commit_hash=${GITHUB_SHA:0:7}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: EMI Ores ${{ env.commit_hash }}
          path: |
            fabric/build/libs/
            forge/build/libs/