on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/*
          modrinth-id: sG4TqDb8
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 974009
          curseforge-name: ""
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
